name: pip

on:
  workflow_dispatch

jobs:
  build:
    name: installing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          gruvybox-factory
    - run: python gruvbox-factory -h
